services:
  ecobrotess-api:
    build:
      context: .
      dockerfile: EcoBrotes/EcoBrotes.Api/Dockerfile
    container_name: ecobrotess-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__db=${DB_CONNECTION_STRING}
      - UseInMemoryDatabase=false
      - ASPNETCORE_HTTP_PORTS=8080
    restart: unless-stopped
