// <auto-generated />
using System;
using EcoBrotes.Infrastructure.DataSource;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EcoBrotes.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EcoBrotes.Domain.EspecieArborea.Entity.EspecieArboreaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MaxHeightMeters")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EspecieArboreaEntity");
                });

            modelBuilder.Entity("EcoBrotes.Domain.JornadasReforestacion.Entity.DetalleArbolJornada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EspecieArboreaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("JornadaReforestacionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EspecieArboreaId");

                    b.HasIndex("JornadaReforestacionId");

                    b.ToTable("DetalleArbolJornada");
                });

            modelBuilder.Entity("EcoBrotes.Domain.JornadasReforestacion.Entity.JornadaReforestacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoUnico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("State")
                        .HasColumnType("smallint");

                    b.Property<int>("TreeMeta")
                        .HasColumnType("integer");

                    b.Property<int>("VolunteerCapacity")
                        .HasColumnType("integer");

                    b.Property<Guid>("ZonaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ZonaUrbanaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ZonaId");

                    b.ToTable("JornadaReforestacion");
                });

            modelBuilder.Entity("EcoBrotes.Domain.ZonaUrbana.Entity.ZonaUrbanaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("ZonaUrbanaEntity");
                });

            modelBuilder.Entity("EcoBrotes.Domain.JornadasReforestacion.Entity.DetalleArbolJornada", b =>
                {
                    b.HasOne("EcoBrotes.Domain.EspecieArborea.Entity.EspecieArboreaEntity", "Especie")
                        .WithMany()
                        .HasForeignKey("EspecieArboreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcoBrotes.Domain.JornadasReforestacion.Entity.JornadaReforestacion", null)
                        .WithMany("DetalleArboles")
                        .HasForeignKey("JornadaReforestacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especie");
                });

            modelBuilder.Entity("EcoBrotes.Domain.JornadasReforestacion.Entity.JornadaReforestacion", b =>
                {
                    b.HasOne("EcoBrotes.Domain.ZonaUrbana.Entity.ZonaUrbanaEntity", "Zona")
                        .WithMany()
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("EcoBrotes.Domain.JornadasReforestacion.Entity.JornadaReforestacion", b =>
                {
                    b.Navigation("DetalleArboles");
                });
#pragma warning restore 612, 618
        }
    }
}
